import { db } from '@/db';
import { tasks } from '@/db/schema';

async function main() {
    const sampleTasks = [
        {
            userId: '123456789',
            title: 'Review budget',
            description: 'Review and update monthly budget spreadsheet',
            status: 'completed',
            priority: 'high',
            category: 'finance',
            dueDate: new Date('2024-01-15').toISOString(),
            completedAt: new Date('2024-01-14').toISOString(),
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            userId: '123456789',
            title: 'Complete workout plan',
            description: 'Finish the 30-minute cardio session',
            status: 'in_progress',
            priority: 'medium',
            category: 'health',
            dueDate: new Date('2024-02-20').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: '987654321',
            title: 'Plan vacation',
            description: 'Research destinations and book flights for summer vacation',
            status: 'pending',
            priority: 'low',
            category: 'personal',
            dueDate: new Date('2024-03-01').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: '987654321',
            title: 'Update resume',
            description: 'Add recent project experience and skills',
            status: 'completed',
            priority: 'urgent',
            category: 'work',
            dueDate: new Date('2024-01-20').toISOString(),
            completedAt: new Date('2024-01-19').toISOString(),
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: '456789123',
            title: 'Grocery shopping',
            description: 'Buy ingredients for meal prep this week',
            status: 'pending',
            priority: 'medium',
            category: 'shopping',
            dueDate: new Date('2024-02-18').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: '456789123',
            title: 'Meeting preparation',
            description: 'Prepare slides and agenda for client presentation',
            status: 'in_progress',
            priority: 'high',
            category: 'work',
            dueDate: new Date('2024-02-22').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: '789123456',
            title: 'Code review',
            description: 'Review pull requests for the new feature branch',
            status: 'completed',
            priority: 'high',
            category: 'work',
            dueDate: new Date('2024-01-22').toISOString(),
            completedAt: new Date('2024-01-21').toISOString(),
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            userId: '789123456',
            title: 'Schedule dentist appointment',
            description: null,
            status: 'cancelled',
            priority: 'low',
            category: 'health',
            dueDate: null,
            completedAt: undefined,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: '321654987',
            title: 'File tax documents',
            description: 'Organize receipts and prepare tax filing documents',
            status: 'pending',
            priority: 'urgent',
            category: 'finance',
            dueDate: new Date('2024-04-15').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            userId: '321654987',
            title: 'Clean garage',
            description: 'Sort and organize items in the garage',
            status: 'in_progress',
            priority: 'low',
            category: 'personal',
            dueDate: new Date('2024-02-28').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            userId: '123456789',
            title: 'Buy birthday gift',
            description: 'Find and purchase gift for sister\'s birthday',
            status: 'completed',
            priority: 'medium',
            category: 'shopping',
            dueDate: new Date('2024-01-28').toISOString(),
            completedAt: new Date('2024-01-27').toISOString(),
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            userId: '987654321',
            title: 'Learn Spanish',
            description: 'Complete daily Spanish lesson on language app',
            status: 'pending',
            priority: 'low',
            category: 'personal',
            dueDate: null,
            completedAt: undefined,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            userId: '456789123',
            title: 'Team standup',
            description: 'Prepare updates for daily team standup meeting',
            status: 'completed',
            priority: 'medium',
            category: 'work',
            dueDate: new Date('2024-01-29').toISOString(),
            completedAt: new Date('2024-01-29').toISOString(),
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            userId: '789123456',
            title: 'Pay credit card bill',
            description: null,
            status: 'pending',
            priority: 'high',
            category: 'finance',
            dueDate: new Date('2024-02-25').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            userId: '321654987',
            title: 'Morning run',
            description: '5km run in the park',
            status: 'completed',
            priority: 'medium',
            category: 'health',
            dueDate: new Date('2024-01-30').toISOString(),
            completedAt: new Date('2024-01-30').toISOString(),
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: '123456789',
            title: 'Book car service',
            description: 'Schedule routine maintenance for the car',
            status: 'in_progress',
            priority: 'medium',
            category: 'personal',
            dueDate: new Date('2024-02-15').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: '987654321',
            title: 'Backup computer files',
            description: 'Create backup of important documents and photos',
            status: 'cancelled',
            priority: 'low',
            category: 'work',
            dueDate: new Date('2024-01-12').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: '456789123',
            title: 'Buy new shoes',
            description: 'Replace worn out running shoes',
            status: 'pending',
            priority: 'medium',
            category: 'shopping',
            dueDate: new Date('2024-03-10').toISOString(),
            completedAt: undefined,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        }
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});