import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        // User 123456789 transactions
        {
            telegramId: '123456789',
            amount: 4200.00,
            type: 'income',
            category: 'salary',
            description: 'Monthly salary payment',
            date: new Date('2024-01-15').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            telegramId: '123456789',
            amount: 85.50,
            type: 'expense',
            category: 'groceries',
            description: 'Weekly grocery shopping',
            date: new Date('2024-01-18').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            telegramId: '123456789',
            amount: 1200.00,
            type: 'expense',
            category: 'rent',
            description: 'Monthly apartment rent',
            date: new Date('2024-01-01').toISOString().split('T')[0],
            account: 'checking',
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-01').toISOString(),
        },
        {
            telegramId: '123456789',
            amount: 45.20,
            type: 'expense',
            category: 'dining',
            description: null,
            date: new Date('2024-01-22').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            telegramId: '123456789',
            amount: 150.00,
            type: 'expense',
            category: 'utilities',
            description: 'Electricity and water bills',
            date: new Date('2024-01-05').toISOString().split('T')[0],
            account: 'checking',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            telegramId: '123456789',
            amount: 750.00,
            type: 'income',
            category: 'freelance',
            description: 'Web design project completion',
            date: new Date('2024-01-20').toISOString().split('T')[0],
            account: 'savings',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // User 987654321 transactions
        {
            telegramId: '987654321',
            amount: 3800.00,
            type: 'income',
            category: 'salary',
            description: 'Bi-weekly paycheck',
            date: new Date('2024-01-14').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            telegramId: '987654321',
            amount: 95.75,
            type: 'expense',
            category: 'groceries',
            description: 'Organic food shopping',
            date: new Date('2024-01-16').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            telegramId: '987654321',
            amount: 65.00,
            type: 'expense',
            category: 'transport',
            description: 'Monthly metro pass',
            date: new Date('2024-01-01').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-01').toISOString(),
        },
        {
            telegramId: '987654321',
            amount: 200.00,
            type: 'expense',
            category: 'shopping',
            description: 'Winter clothing',
            date: new Date('2024-01-12').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            telegramId: '987654321',
            amount: 500.00,
            type: 'income',
            category: 'bonus',
            description: 'Performance bonus',
            date: new Date('2024-01-25').toISOString().split('T')[0],
            account: 'savings',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            telegramId: '987654321',
            amount: 120.00,
            type: 'expense',
            category: 'healthcare',
            description: 'Doctor appointment',
            date: new Date('2024-01-19').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },

        // User 456789123 transactions
        {
            telegramId: '456789123',
            amount: 4500.00,
            type: 'income',
            category: 'salary',
            description: null,
            date: new Date('2024-01-30').toISOString().split('T')[0],
            account: 'checking',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            telegramId: '456789123',
            amount: 320.00,
            type: 'expense',
            category: 'entertainment',
            description: 'Concert tickets',
            date: new Date('2024-02-03').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            telegramId: '456789123',
            amount: 78.30,
            type: 'expense',
            category: 'groceries',
            description: 'Weekend shopping',
            date: new Date('2024-02-05').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            telegramId: '456789123',
            amount: 250.00,
            type: 'income',
            category: 'gift',
            description: 'Birthday gift from parents',
            date: new Date('2024-02-10').toISOString().split('T')[0],
            account: 'savings',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            telegramId: '456789123',
            amount: 180.00,
            type: 'expense',
            category: 'shopping',
            description: null,
            date: new Date('2024-02-08').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },

        // User 789123456 transactions
        {
            telegramId: '789123456',
            amount: 3200.00,
            type: 'income',
            category: 'salary',
            description: 'Monthly salary - part time',
            date: new Date('2024-02-01').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            telegramId: '789123456',
            amount: 1100.00,
            type: 'expense',
            category: 'rent',
            description: 'Studio apartment rent',
            date: new Date('2024-02-01').toISOString().split('T')[0],
            account: 'checking',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            telegramId: '789123456',
            amount: 42.80,
            type: 'expense',
            category: 'dining',
            description: 'Pizza night with friends',
            date: new Date('2024-02-12').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            telegramId: '789123456',
            amount: 600.00,
            type: 'income',
            category: 'freelance',
            description: 'Mobile app development',
            date: new Date('2024-02-15').toISOString().split('T')[0],
            account: 'savings',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            telegramId: '789123456',
            amount: 35.50,
            type: 'expense',
            category: 'transport',
            description: null,
            date: new Date('2024-02-14').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            telegramId: '789123456',
            amount: 125.00,
            type: 'expense',
            category: 'groceries',
            description: 'Monthly grocery haul',
            date: new Date('2024-02-07').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },

        // User 321654987 transactions
        {
            telegramId: '321654987',
            amount: 5000.00,
            type: 'income',
            category: 'salary',
            description: 'Senior developer salary',
            date: new Date('2024-02-15').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 1500.00,
            type: 'expense',
            category: 'rent',
            description: '2-bedroom apartment',
            date: new Date('2024-02-01').toISOString().split('T')[0],
            account: 'checking',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 450.00,
            type: 'income',
            category: 'investment',
            description: 'Dividend payout',
            date: new Date('2024-02-20').toISOString().split('T')[0],
            account: 'savings',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 95.00,
            type: 'expense',
            category: 'utilities',
            description: 'Internet and cable',
            date: new Date('2024-02-05').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 280.00,
            type: 'expense',
            category: 'healthcare',
            description: 'Dental cleaning and checkup',
            date: new Date('2024-02-18').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 110.25,
            type: 'expense',
            category: 'groceries',
            description: null,
            date: new Date('2024-02-22').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            telegramId: '321654987',
            amount: 75.40,
            type: 'expense',
            category: 'entertainment',
            description: 'Movie theater and snacks',
            date: new Date('2024-02-25').toISOString().split('T')[0],
            account: 'main',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        }
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});